export const USER = {
  OPENAI: "openai",
  GEMINI: "gemini",
  ME_OPENAI: "user",
  ME_GEMINI: "user_gemini",
  SYSTEM: "system",
};


export const PROCESS = {
  ELABORATING: "ELABORATING",
  ELABORATED: "ELABORATED",
  GENERATE_OBJECT: "GENERATE_OBJECT",
  GENERATE_OBJECT_DONE: "GENERATE_OBJECT_DONE",
  INVALID_INPUT: "INVALID_INPUT",
  ERROR:"ERROR"
}

export const PROCESS_STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  FAILED: "FAILED",
  SUCCESS: "SUCCESS",
  INFO: "INFO",
}